#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# remove surface

rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f constant/triSurface/passenger_head.eMesh > /dev/null 2>&1
rm -f constant/triSurface/passenger_body.eMesh > /dev/null 2>&1
rm -f constant/polyMesh/boundary

cleanCase

#------------------------------------------------------------------------------
