#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication blockMesh

runApplication dos2unix LIFT.msh
 
runApplication fluent3DMeshToFoam LIFT.msh 
 
runApplication surfaceFeatures

runApplication snappyHexMesh -overwrite

sed -i 's/passenger_/ /g' ./constant/polyMesh/boundary

runApplication changeDictionary
 
runApplication checkMesh 

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar

